#ifndef UI_LANGUAGE_H
#define UI_LANGUAGE_H

enum ui_language {
	UI_LANG_EN = 0,
	UI_LANG_ZH_CN,
	UI_LANG_ZH_TW,
	UI_LANG_COUNT
};

enum ui_text_id {
	UI_TEXT_ON = 0,
	UI_TEXT_OFF,
	UI_TEXT_RESUME_GAME,
	UI_TEXT_SAVE_STATE,
	UI_TEXT_LOAD_STATE,
	UI_TEXT_DISC_CONTROL,
	UI_TEXT_CHEATS,
	UI_TEXT_OPTIONS,
	UI_TEXT_RESET_GAME,
	UI_TEXT_LOAD_NEW_GAME,
	UI_TEXT_ABOUT,
	UI_TEXT_EXIT,
	UI_TEXT_AUDIO_VIDEO,
	UI_TEXT_EMULATOR_OPTIONS,
	UI_TEXT_PLAYER_CONTROLS,
	UI_TEXT_EMULATOR_HOTKEYS,
	UI_TEXT_SAVE_CONFIG,
	UI_TEXT_SHOW_FPS,
	UI_TEXT_SHOW_CPU_USAGE,
	UI_TEXT_DISPLAY_MODE,
	UI_TEXT_ZOOM_LEVEL,
	UI_TEXT_SCREEN_PANNING,
	UI_TEXT_SCREEN_ROTATION,
	UI_TEXT_SCALING_FILTER,
	UI_TEXT_AUDIO_BUFFER,
	UI_TEXT_AUDIO_ADJUSTMENT,
	UI_TEXT_USE_SRM_SAVES,
	UI_TEXT_SAVE_GLOBAL_CONFIG,
	UI_TEXT_SAVE_GAME_CONFIG,
	UI_TEXT_DELETE_GAME_CONFIG,
	UI_TEXT_RESTORE_DEFAULTS,
	UI_TEXT_ABOUT_TO_DELETE,
	UI_TEXT_ARE_YOU_SURE,
	UI_TEXT_BACK,
	UI_TEXT_LOAD_FAILED,
	UI_TEXT_SAVE_FAILED,
	UI_TEXT_DEFAULTS_RESTORED,
	UI_TEXT_CONFIG_SAVED,
	UI_TEXT_CONFIG_WRITE_FAILED,
	UI_TEXT_LOAD_STATE_TITLE,
	UI_TEXT_SAVE_STATE_TITLE,
	UI_TEXT_SLOT_FMT,
	UI_TEXT_PLAYER_CONTROLS_FMT,
	UI_TEXT_EMULATOR_CONTROLS,
	UI_TEXT_PRESS_BIND,
	UI_TEXT_PRESS_OTHER_DEVICE,
	UI_TEXT_TEST_ENGLISH_FALLBACK,
	UI_TEXT_COUNT
};

int ui_language_parse_checked(const char *code, enum ui_language *language);
enum ui_language ui_language_parse(const char *code);
void ui_language_set(enum ui_language language);
enum ui_language ui_language_current(void);
const char *ui_language_code(void);
const char *ui_text(enum ui_text_id id);

#endif
