#!/usr/bin/env python3

import csv
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "locales" / "ui.tsv"
OUTPUT = ROOT / "ui_catalog_data.h"
HEADER = ["key", "en", "zh_CN", "zh_TW"]
FALLBACK_ROW = ["test_english_fallback", "English fallback", "", ""]
PRINTF_CONVERSION = re.compile(
	r"%(?:(?P<position>[1-9][0-9]*)\$)?"
	r"[-+ #0']*"
	r"(?P<width>\*|\d+)?"
	r"(?:\.(?P<precision>\*|\d*))?"
	r"(?P<length>hh|h|ll|l|j|z|t|L)?"
	r"(?P<conversion>[diouxXfFeEgGaAcspn%])"
)


def c_string(value):
	return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def printf_signature(value):
	signature = []
	offset = 0

	while True:
		percent = value.find("%", offset)
		if percent < 0:
			break
		match = PRINTF_CONVERSION.match(value, percent)
		if match is None:
			raise ValueError("invalid printf conversion")
		conversion = match.group("conversion")
		if conversion == "%":
			if match.group(0) != "%%":
				raise ValueError("invalid escaped percent conversion")
		elif conversion == "n":
			raise ValueError("forbidden printf conversion: %n")
		else:
			position = match.group("position")
			prefix = (position + "$") if position else ""
			if match.group("width") == "*":
				signature.append(prefix + "*")
			if match.group("precision") == "*":
				signature.append(prefix + ".*")
			signature.append(
				prefix + (match.group("length") or "") + conversion
			)
		offset = match.end()
	return tuple(signature)


def read_catalog():
	with SOURCE.open("r", encoding="utf-8", newline="") as source:
		rows = list(csv.reader(source, delimiter="\t"))

	if not rows or rows[0] != HEADER:
		raise ValueError("catalog header must be: key, en, zh_CN, zh_TW")

	seen = {FALLBACK_ROW[0]}
	catalog = []
	for line_number, row in enumerate(rows[1:], start=2):
		if len(row) != 4:
			raise ValueError("line %d must contain exactly four columns" %
					 line_number)
		if any("\n" in cell or "\r" in cell for cell in row):
			raise ValueError("line %d contains an embedded newline" %
					 line_number)
		key, english, zh_cn, zh_tw = row
		if key in seen:
			raise ValueError("duplicate catalog key: %s" % key)
		if not english:
			raise ValueError("missing English text for key: %s" % key)
		english_signature = printf_signature(english)
		for language, translation in (
			("zh_CN", zh_cn),
			("zh_TW", zh_tw),
		):
			if translation and printf_signature(translation) != english_signature:
				raise ValueError(
					"printf signature mismatch for %s in %s" %
					(key, language)
				)
		seen.add(key)
		catalog.append([key, english, zh_cn, zh_tw])

	catalog.append(FALLBACK_ROW)
	return catalog


def generate(catalog):
	lines = [
		"/* Generated by tools/gen_ui_catalog.py. Do not edit. */",
		"#ifndef UI_CATALOG_DATA_H",
		"#define UI_CATALOG_DATA_H",
		"",
		"static const char *const "
		"ui_catalog[UI_TEXT_COUNT][UI_LANG_COUNT] = {",
	]
	for key, english, zh_cn, zh_tw in catalog:
		enum_name = "UI_TEXT_" + key.upper()
		lines.append("\t[%s] = { %s, %s, %s }," %
			     (enum_name, c_string(english), c_string(zh_cn),
			      c_string(zh_tw)))
	lines.extend([
		"};",
		"",
		"#endif",
		"",
	])
	return "\n".join(lines)


def main():
	with OUTPUT.open("w", encoding="utf-8", newline="\n") as output:
		output.write(generate(read_catalog()))


if __name__ == "__main__":
	main()
