#!/usr/bin/env python3

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "locales" / "ui.tsv"
OUTPUT = ROOT / "ui_catalog_data.h"
HEADER = ["key", "en", "zh_CN", "zh_TW"]
FALLBACK_ROW = ["test_english_fallback", "English fallback", "", ""]


def c_string(value):
	return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def read_catalog():
	with SOURCE.open("r", encoding="utf-8", newline="") as source:
		rows = list(csv.reader(source, delimiter="\t"))

	if not rows or rows[0] != HEADER:
		raise ValueError("catalog header must be: key, en, zh_CN, zh_TW")

	seen = {FALLBACK_ROW[0]}
	catalog = []
	for line_number, row in enumerate(rows[1:], start=2):
		if len(row) != 4:
			raise ValueError("line %d must contain exactly four columns" %
					 line_number)
		if any("\n" in cell or "\r" in cell for cell in row):
			raise ValueError("line %d contains an embedded newline" %
					 line_number)
		key, english, zh_cn, zh_tw = row
		if key in seen:
			raise ValueError("duplicate catalog key: %s" % key)
		if not english:
			raise ValueError("missing English text for key: %s" % key)
		seen.add(key)
		catalog.append([key, english, zh_cn, zh_tw])

	catalog.append(FALLBACK_ROW)
	return catalog


def generate(catalog):
	lines = [
		"/* Generated by tools/gen_ui_catalog.py. Do not edit. */",
		"#ifndef UI_CATALOG_DATA_H",
		"#define UI_CATALOG_DATA_H",
		"",
		"static const char *const "
		"ui_catalog[UI_TEXT_COUNT][UI_LANG_COUNT] = {",
	]
	for key, english, zh_cn, zh_tw in catalog:
		enum_name = "UI_TEXT_" + key.upper()
		lines.append("\t[%s] = { %s, %s, %s }," %
			     (enum_name, c_string(english), c_string(zh_cn),
			      c_string(zh_tw)))
	lines.extend([
		"};",
		"",
		"#endif",
		"",
	])
	return "\n".join(lines)


def main():
	with OUTPUT.open("w", encoding="utf-8", newline="\n") as output:
		output.write(generate(read_catalog()))


if __name__ == "__main__":
	main()
